### ISSUE TITLE
Skill does not work

### ISSUE THREAD

**Issue by rigved** [MycroftAI/skill-platform-patch#2]
This skill does not work any more because the following URL is no longer present:

https://mycroft.ai/platform_patch_1

Would it make more sense to use "apt-cache" and "apt-get" to handle this skill's task instead of using a URL?

**Comment by MatthewScholefield** [comment]
Thank you for reporting this. It has been fixed and comments have been added so it makes a little more sense now. It uses the URL since it does a few different things that make sense to run from a bash script. It both replaces the crontab and updates the GPG key.
